import time
time.sleep(.5)

print("\n\n\t\t\t\t\t\t**************************************************")
time.sleep(.5)
print("\t\t\t\t\t\t**************                                   *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                   *               *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                  *                *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                * *    *           *")
time.sleep(.5)
print("\t\t\t\t\t\t**************               *  *  * * *         *")
time.sleep(.5)
print("\t\t\t\t\t\t**************               *  *   * *          *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                *  *               *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                  * *              *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                     *             *")
time.sleep(.5)
print("\t\t\t\t\t\t**************                                   *")
time.sleep(.5)
print("\t\t\t\t\t\t**************************************************")
time.sleep(1)
print("\n\t\t\t\t\t\t\tH A P P Y  I N D E P E N D E N C E  D A Y")
print("")
